config/routes.rb
SimpleCatalog::Application.routes.draw do
  resources :zones do as_routes end

  resources :sectors do as_routes end

  resources :disciplines do as_routes end

  resources :addresses do
    as_routes
    collection do
      get 'domains'
      post 'rebuild'
    end
  end

  devise_for :users

  resources :users do
    as_routes
  end

  root :to => 'guest#domains'

  get '/catalog(/:sector_id(/:discipline_id))' => 'guest#catalog', :as => :catalog
  get '/domains(.:format)' => 'guest#domains'
  match '/guest/:action' => 'guest'

end

app/models/zone.rb
class Zone < ActiveRecord::Base
  attr_accessible :description, :suffix

  validates :suffix, :presence => true, :uniqueness => true

  before_save do |zone|
    zone.suffix = Unicode::downcase(zone.suffix)
    zone.suffix = "."+zone.suffix unless zone.suffix.start_with? "."
  end

end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_filter :authenticate_user!
  active_scaffold :zone do |conf|
    conf.columns = [:suffix, :description]
  end
end 

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/zones/index.html.erb
<div class="btn-toolbar">
  <a href="<%= rebuild_addresses_path %>" class="btn">Перестроить базу доменов</a>
<div>

<%= render :super %>

app/views/zones/list.html.erb
<p>Здесь перечислены доменные зоны, в которых свободно делегируются домены третьего уровня и выше (Например: site.org.ru). Пожалуйста, добавляйте сюда суффиксы таких зон (как <strong>.org.ru</strong> из примера), чтобы избежать включения слишком большого количества сайтов с разной тематикой в список разрешённых ресурсов. После добавления, нажмите кнопку «Перестроить базу доменов» и немного подождите.</p>

<div class="btn-toolbar">
  <%= link_to "Перестроить базу доменов", rebuild_addresses_path, :method => :post, :class => "btn" %>
<div>

<%= render :super %>