config/routes.rb
SimpleCatalog::Application.routes.draw do
  resources :zones do as_routes end

  resources :sectors do as_routes end

  resources :disciplines do as_routes end

  resources :addresses do
    as_routes
    collection do
      get 'domains'
      post 'rebuild'
    end
  end

  devise_for :users

  resources :users do
    as_routes
  end

  root :to => 'guest#domains'

  get '/catalog(/:sector_id(/:discipline_id))' => 'guest#catalog', :as => :catalog
  get '/domains(.:format)' => 'guest#domains'
  match '/guest/:action' => 'guest'

end

app/views/layouts/_main_menu.html.haml
%li
  = link_to "Веб-сайт АмГУ", "http://www.amursu.ru/"
%li{:class => ("active" if params[:action] == "domains")}
  = link_to "Список доступных сайтов", root_path
%li{:class => ("active" if params[:action] == "catalog")}
  = link_to "Каталог ссылок по дисциплинам", catalog_path
- if user_signed_in?
  %li{:class => ("active" if params[:controller] == "addresses")}
    = link_to "Интернет-адреса", addresses_path
  %li{:class => ("active" if params[:controller] == "disciplines")}
    = link_to "Дисциплины", disciplines_path
  %li{:class => ("active" if params[:controller] == "sectors")}
    = link_to "Отрасли знаний", sectors_path
  %li{:class => ("active" if params[:controller] == "zones")}
    = link_to "Доменные зоны", zones_path

app/views/layouts/_user_menu.html.haml
- if user_signed_in?
  %li{:class => ("active" if params[:controller].start_with? "devise")}
    = link_to t("devise.labels.sign_out"), destroy_user_session_path, :method => :delete
- else
  %li{:class => ("active" if params[:controller].start_with? "devise")}
    = link_to t("devise.labels.sign_in"), new_user_session_path

app/views/layouts/application.html.haml
!!!
%html{lang: I18n.locale}
  %head
    %meta{charset: "utf-8"}
    %title #{t("application.name")}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = analytics_init if Rails.env.production?
  %body
    .navbar
      .navbar-inner
        .container-fluid
          %ul.nav
            = render "layouts/main_menu"
          %ul.nav.pull-right
            = render "layouts/user_menu"
    .container-fluid
      .row-fluid
        - unless notice.nil?
          %p.alert.alert-info= notice
        - unless alert.nil?
          %p.alert.alert-error= alert

        = yield

      .ajax_spinner
        .ajax_spinner_image